Repository Like-Lion-Team-WAY/WAY, pull requests merged in 2024-07, with the labels that each got.

#8 [Setting] layerArchitecture_ddd
  src/main/java/like/lion/way/admin/controller/hello
  src/main/java/like/lion/way/admin/domain/hello
  src/main/java/like/lion/way/admin/repository/hello
  src/main/java/like/lion/way/admin/service/hello
  src/main/java/like/lion/way/alarm/controller/hello
  src/main/java/like/lion/way/alarm/domain/hello
  src/main/java/like/lion/way/alarm/repository/hello
  src/main/java/like/lion/way/alarm/service/hello
  src/main/java/like/lion/way/board/controller/hello
  src/main/java/like/lion/way/board/domain/hello
  src/main/java/like/lion/way/board/repository/hello
  src/main/java/like/lion/way/board/service/hello
  src/main/java/like/lion/way/chat/controller/hello
  src/main/java/like/lion/way/chat/domain/hello
  src/main/java/like/lion/way/chat/repository/hello
  src/main/java/like/lion/way/chat/service/hello
  src/main/java/like/lion/way/config/hello
  src/main/java/like/lion/way/feed/controller/hello
  src/main/java/like/lion/way/feed/domain/hello
  src/main/java/like/lion/way/feed/post/hello
  src/main/java/like/lion/way/feed/repository/hello
  src/main/java/like/lion/way/feed/service/hello
  src/main/java/like/lion/way/jwt/exception/hello
  src/main/java/like/lion/way/jwt/filter/hello
  src/main/java/like/lion/way/jwt/service/hello
  src/main/java/like/lion/way/jwt/util/hello
  src/main/java/like/lion/way/security/hello
  src/main/java/like/lion/way/user/controller/hello
  src/main/java/like/lion/way/user/domain/hello
  src/main/java/like/lion/way/user/repository/hello
  src/main/java/like/lion/way/user/service/hello
Labels: ⚙ Setting

#12 [Feature] thymeleaf layout fragments
  build.gradle
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/static/css/main.css
  src/main/resources/templates/fragments/aside.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/layouts/layout.html
  src/main/resources/templates/pages/user/test.html
Labels: ⚙ Setting, 🎨 Html&css

#20 [Feature] user entity domain
  src/main/java/like/lion/way/user/controller/hello
  src/main/java/like/lion/way/user/domain/User.java
  src/main/java/like/lion/way/user/domain/hello
  src/main/java/like/lion/way/user/repository/UserRepository.java
  src/main/java/like/lion/way/user/repository/hello
  src/main/java/like/lion/way/user/service/UserService.java
  src/main/java/like/lion/way/user/service/hello
Labels: ✨ Feature

#21 [Feature] Board 도메인 엔티티 생성
  src/main/java/like/lion/way/board/controller/hello
  src/main/java/like/lion/way/board/domain/Board.java
  src/main/java/like/lion/way/board/domain/BoardPost.java
  src/main/java/like/lion/way/board/domain/BoardPostComment.java
  src/main/java/like/lion/way/board/domain/BoardPostLike.java
  src/main/java/like/lion/way/board/domain/BoardPostScrap.java
  src/main/java/like/lion/way/board/domain/hello
  src/main/java/like/lion/way/board/repository/BoardPostCommentRepository.java
  src/main/java/like/lion/way/board/repository/BoardPostLikeRepository.java
  src/main/java/like/lion/way/board/repository/BoardPostRepository.java
  src/main/java/like/lion/way/board/repository/BoardPostScrapRepository.java
  src/main/java/like/lion/way/board/repository/BoardRepository.java
  src/main/java/like/lion/way/board/repository/hello
  src/main/java/like/lion/way/board/service/hello
Labels: ✨ Feature

#26 [Feature] implement crud api about community board
  build.gradle
  src/main/java/like/lion/way/board/api/BoardController.java
  src/main/java/like/lion/way/board/api/request/BoardCreateRequest.java
  src/main/java/like/lion/way/board/api/request/BoardEditRequest.java
  src/main/java/like/lion/way/board/application/BoardService.java
  src/main/java/like/lion/way/board/application/BoardServiceImpl.java
  src/main/java/like/lion/way/board/application/request/BoardCreateServiceRequest.java
  src/main/java/like/lion/way/board/application/request/BoardEditServiceRequest.java
  src/main/java/like/lion/way/board/domain/AnonymousPermission.java
  src/main/java/like/lion/way/board/domain/Board.java
  src/main/java/like/lion/way/board/domain/BoardPost.java
  src/main/java/like/lion/way/user/repository/UserRepository.java
Labels: ✨ Feature

#28 [Feature] security+JWT+OAuth2
  .gitignore
  build.gradle
  src/main/java/like/lion/way/config/PasswordEncoderConfig.java
  src/main/java/like/lion/way/config/SecurityConfig.java
  src/main/java/like/lion/way/config/hello
  src/main/java/like/lion/way/jwt/exception/CustomAuthenticationEntryPoint.java
  src/main/java/like/lion/way/jwt/exception/JwtExceptionCode.java
  src/main/java/like/lion/way/jwt/exception/hello
  src/main/java/like/lion/way/jwt/filter/JwtRequestFilter.java
  src/main/java/like/lion/way/jwt/filter/hello
  src/main/java/like/lion/way/jwt/service/JwtUserDetailsService.java
  src/main/java/like/lion/way/jwt/service/hello
  src/main/java/like/lion/way/jwt/util/JwtUtil.java
  src/main/java/like/lion/way/jwt/util/hello
  src/main/java/like/lion/way/user/controller/UserController.java
  src/main/java/like/lion/way/user/controller/restcontroller/UserRestController.java
  src/main/java/like/lion/way/user/domain/Role.java
  src/main/java/like/lion/way/user/domain/RoleType.java
  src/main/java/like/lion/way/user/domain/User.java
  src/main/java/like/lion/way/user/oauth2/dto/OAuthAttributes.java
  src/main/java/like/lion/way/user/oauth2/handler/CustomOAuth2FailureHandler.java
  src/main/java/like/lion/way/user/oauth2/handler/CustomOAuth2SuccessHandler.java
  src/main/java/like/lion/way/user/oauth2/service/CustomOAuth2UserService.java
  src/main/java/like/lion/way/user/repository/UserRepository.java
  src/main/java/like/lion/way/user/service/UserService.java
  src/main/java/like/lion/way/user/service/serviceImpl/UserServiceImpl.java
  src/main/resources/static/css/main.css
  src/main/resources/static/css/mainpage.css
  src/main/resources/templates/pages/common/main.html
  src/main/resources/templates/pages/user/login.html
  src/main/resources/templates/pages/user/loginInfo.html
Labels: ✨ Feature, 📬 API
